# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, lib, config, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "xhci_pci"
    "firewire_ohci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/3244d334-63d6-490c-85c5-739006eaf971";
      fsType = "ext4";
    };
  fileSystems."/home/mar/disks/1TB-old" = {
    device = "/dev/disk/by-uuid/e70a18c8-b639-433b-b3f9-55a5b90b5329";
    fsType = "ext4";
  };
  fileSystems."/home/mar/disks/1TB-2024" = {
    device = "/dev/disk/by-uuid/05beb860-0998-4dcc-9145-a7379368dac4";
    fsType = "ext4";
  };
  fileSystems."/home/mar/disks/256GB" = {
    device = "/dev/disk/by-uuid/d2929f64-39bd-44a9-a697-aa13ea0279f1";
    fsType = "ext4";
  };
  fileSystems."/home/mar/disks/128GB" = {
    device = "/dev/disk/by-uuid/8816b838-6024-4dfc-9559-eabc9665760e";
    fsType = "ext4";
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/1B8B-D705";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [{ device = "/dev/disk/by-uuid/13b1770c-0799-4bfa-b497-2f8a23903a01"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s1.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
