graph LR

x --> fungable
x --> nonfungable
nonfungable --> authentication
fungable --> money
money --> power
time --> power
inteligence -->structure


symbols --> structure
symbols --> inteligence
symbols --> entropy 
symbols --> energy 
symbols --> power 
symbols --> money
symbols --> learning
symbols --> energy 

