inputs:
{ pkgs, config, ... }:
let user = "mar"; in
{
  nixpkgs.overlays = [ inputs.nur.overlay ];


  #imports =[ inputs.home-manager.nixosModules.home-manager ];
  config.programs.zsh.enabled = true;
  users.users.${user} = {
    isNormalUser = true;
    shell = pkgs.zsh;
    group = user;
  };


  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
  #home-manager.sharedModules = my-homemanager-modules;
  home-manager.users.${user} = {
    imports = (builtins.attrValues inputs.my-modules.hmModules.x86_64-linux) ++ [
      {
        modules.zsh.enable = true;
        modules.zellij.enable = true;
        modules.firefox.enable = true;
        modules.autorandr.enable = false;
        modules.bspwm.enable = false;
        modules.dunst.enable = true;
        modules.kitty.enable = true;
        modules.newsboat.enable = true;
        modules.polybar.enable = false;
        modules.xmonad.enable = false;
        modules.spotifyd.enable = false;
        modules.other.enable = true;
        modules.myPackages.enable = true;
        modules.cloneDefaultRepos.enable = true;

        programs.home-manager.enable = true;
        programs.bash.enable = true;

        home = {
          stateVersion = "22.11";
          username = user;
          #homeDirectory = "/home/${user}";

          packages = [ pkgs.vim ];

          sessionVariables = {
            EDITOR = "vim";
            TEST_VARIABLE = "THISISATESTSTRING";
          };

          #file.".config/nixpkgs/config.nix" = {
          #  text = ''
          #    { allowUnfree = true; }
          #  '';
          #};
          file."git/txt" = {
            text = "generated by homemanager";
          };

          sessionPath = [
            "$HOME/go/bin"
            "$HOME/.local/bin"
            "$HOME/bin"
          ];
        };

      }
    ];
  };
}
