inputs:
{ pkgs, config, ... }:
{
  nixpkgs.overlays = [ inputs.nur.overlay ];
  nixpkgs.config.allowUnfree = true;

  #modules.myNvim.enable = true;
  imports = [
    inputs.home-manager.nixosModules.home-manager
    inputs.nixos-wsl.nixosModules.wsl
  ];

  wsl = {
    #enable = true;
    enable = false;
    wslConf.automount.root = "/mnt";
    defaultUser = "nixos";
    startMenuLaunchers = true;

    # Enable native Docker support
    # docker-native.enable = true;
    # Enable integration with Docker Desktop (needs to be installed)
    # docker-desktop.enable = true;
  };

  programs.zsh.enable = true;
  users = {
    #groups.nixos = { };
    groups.mar = { };
    #users.nixos = {
    #  shell = pkgs.bash;
    #  #isSystemUser = true;
    #  group = "nixos";
    #};
    users.mar = {
      isNormalUser = true;
      shell = pkgs.zsh;
      group = "mar";
    };
  };


  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
  #home-manager.sharedModules = my-homemanager-modules;
  home-manager.users =
    let
      createUserConf = user:
        {
          imports = builtins.attrValues inputs.my-modules.hmModules.${pkgs.system} ++ [
            # my-homemanager-modules ++ [
            {
              modules.zsh.enable = true;
              modules.zellij.enable = true;
              modules.firefox.enable = true;
              modules.autorandr.enable = false;
              modules.bspwm.enable = false;
              modules.dunst.enable = true;
              modules.kitty.enable = true;
              modules.newsboat.enable = true;
              modules.polybar.enable = false;
              modules.xmonad.enable = false;
              modules.spotifyd.enable = false;
              modules.other.enable = true;
              #modules.myPackages.enable = true;
              modules.cloneDefaultRepos.enable = true;

              programs.home-manager.enable = true;
              programs.bash.enable = true;

              home = {
                stateVersion = "22.11";
                username = user;
                #homeDirectory = "/home/${user}";

                packages = [ pkgs.vim ];

                sessionVariables = {
                  EDITOR = "vim";
                  TEST_VARIABLE = "THISISATESTSTRING";
                };

                file.".config/nixpkgs/config.nix" = {
                  text = ''
                    { allowUnfree = true; }
                  '';
                };
                file."git/txt" = {
                  text = "generated by homemanager";
                };

                sessionPath = [
                  "$HOME/go/bin"
                  "$HOME/.local/bin"
                  "$HOME/bin"
                ];
              };

            }
          ];
        };
    in
    {
      mar = createUserConf "mar";
      #nixos = createUserConf "nixos";
    };

  environment.systemPackages = with pkgs; [
    wget
    curl
    lf
    htop
    git
    zellij
  ];

  # Enable nix flakes
  nix = {
    settings.auto-optimise-store = true;
    #    package = pkgs.nixUnstable;
    settings.experimental-features = [ "nix-command" "flakes" ];
  };

  #system.stateVersion = "22.11";
}
